name: Latest douban activities workflow
on:
  schedule:
    # Runs every 2 hour
    - cron: "0 */2 * * *"

jobs:
  update-readme-with-douban-activities:
    name: Update this repo's README with douban activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      # - uses: actions/checkout@v2
      - name: Update README.md with douban user's activities
        uses: dongweiming/douban-activity-readme@v1
        with:
          uid: 136069238
          max_count: 10
      - name: Commit & Push changes
        uses: actions-js/push@4decc2887d2770f29177082be3c8b04d342f5b64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
